export const GET_ITEM_BEGIN = 'GET_ITEM_BEGIN';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';

export const ADD_ITEM_BEGIN = 'ADD_ITEM_BEGIN';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'Add_ITEM_FAILURE';

export const GET_ITEMS_BEGIN = 'GET_ITEMS_BEGIN';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const GET_LOCATION_BEGIN = 'GET_LOCATION_BEGIN';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';

export const GET_LOCATIONS_BEGIN = 'GET_LOCATIONS_BEGIN';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';

export const GET_RETAILER_BEGIN = 'GET_RETAILER_BEGIN';
export const GET_RETAILER_SUCCESS = 'GET_RETAILER_SUCCESS';
export const GET_RETAILER_FAILURE = 'GET_RETAILER_FAILURE';

export const GET_RETAILERS_BEGIN = 'GET_RETAILERS_BEGIN';
export const GET_RETAILERS_SUCCESS = 'GET_RETAILERS_SUCCESS';
export const GET_RETAILERS_FAILURE = 'GET_RETAILERS_FAILURE';